# https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html
version: "3.8"

services:
  zendog-dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: zendog-dynamodb
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  zendog-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zendog-api
    ports:
      - "8888:8888"
    depends_on:
      - "zendog-dynamodb"
    environment:
      FRONTEND_DOMAIN: ${FRONTEND_DOMAIN}
      DYNAMODB_ENDPOINT: ${DYNAMODB_ENDPOINT}
      DYNAMODB_TABLE_NAME: ${DYNAMODB_TABLE_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
