# https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html
version: "3.8"

services:
  zendog-dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: zendog-dynamodb
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  zendog-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zendog-api
    ports:
      - "8888:8888"
    depends_on:
      - "zendog-dynamodb"
    environment:
      FRONTEND_DOMAIN: "http://127.0.0.1:3006"
      DYNAMODB_ENDPOINT: "http://zendog-dynamodb:8000"
      DYNAMODB_TABLE_NAME: "zendog"
      AWS_ACCESS_KEY_ID: "xx"
      AWS_SECRET_ACCESS_KEY: "xx"
      AWS_REGION: "us-east-2"
